server:
  port: 8080

spring:
  application:
    name: taskforge 
  datasource:
    url: jdbc:postgresql://database:5432/taskforge_db
    username: admin
    password: admin
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: dGhpc19pc19hX3ZhbGlkX2Jhc2U2NF9rZXlfZm9yX3Rhc2tmb3JnZQ==
    expiration-ms: 3600000 # 1 hour in milliseconds